# Generated by Django 4.1.7 on 2023-02-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='Nickname')),
                ('profile_photo', models.ImageField(height_field=300, upload_to='', verbose_name='profile_photo', width_field=300)),
                ('register_date', models.DateField()),
                ('last_visit', models.DateField()),
                ('number_of_posts', models.IntegerField()),
            ],
        ),
    ]
