# Generated by Django 4.1.7 on 2023-02-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_profile_number_of_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
