# Generated by Django 4.1.7 on 2023-02-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_number_of_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
